name: Main CI
on: push
jobs:
  test-node:
    strategy:
      matrix:
        node: ["10.x", "12.x", "14.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ./.cache/yarn
          key: yarn-packages-waffle-${{ matrix.node }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - name: setup-solc
        run: sudo cp ./.github/workflows/solc /bin
      - run: yarn build
      - run: yarn test:others
  example-mock-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Example - Mock contracts
        working-directory: ./examples/mock-contracts
        run: yarn install && yarn lint && yarn build && yarn test
  example-change-balance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Example - Change balance
        working-directory: ./examples/change-balance
        run: yarn install && yarn lint && yarn build && yarn test
  example-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Example - Basic
        working-directory: ./examples/basic
        run: yarn install && yarn lint && yarn build && yarn test
  example-called-on-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Example - calledOnContract
        working-directory: ./examples/called-on-contract
        run: yarn install && yarn lint && yarn build && yarn test
  example-ens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Example - ens
        working-directory: ./examples/ens
        run: yarn install && yarn lint && yarn build && yarn test
  docs-and-linter:
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}
      - name: Make html
        run: make html
        working-directory: ${{ env.working-directory }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - run: yarn install --frozen-lockfile
      - name: linter
        run: yarn install
